# Remove Duplicates
In this short tutorial I show how to remove duplicates from a dataframe, using the `drop_duplicates()` function provided by the `pandas` library.
Duplicates removal is a technique used to preprocess data. Data preprocessing also includes:
* missing values
* standardization
* normalization
* formatting
* binning.

## Data import
Firstly, I import the Python `pandas` library and then I read the CSV file through the `read_csv()` function.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/SSN FDP/Leni.csv')
df.head()

                       author                   channel  ...        time  votes
0            Suganya Arumugam  UC_EOwRWhd65qJ5QOZTAlTeA  ...  2 days ago      0
1  Army Public School Dagshai  UC5xN5xDJpIjIzAk7N5BTGJA  ...  3 days ago      0
2                  Magima T.A  UCZ9QVy5nhEsSk_fKtN1CIkA  ...  7 days ago      0
3                   unnimaya   UCAy8cxcLl-wR6BOB3CWAsuA  ...  7 days ago      0
4                 alex philip  UCX62wvhlEwZ9HX5_Rsl15Ig  ...  7 days ago      0

[5 rows x 8 columns]

Now I list the number of records contained in the dataframe. I exploit the `shape` attributes, which shows the number of rows and the number of columns of the dataframe.

In [4]:
df.shape

(45, 8)

## Check for the presence of duplicates
In order to check whether a record is duplicated or not, I can exploit the `duplicated()` function, which returns `True` if a record has other duplicates, `False` otherwise.

In [13]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
dtype: bool

I can use the `duplicated()` function also on a subset of columns of the dataframe. In this case, I must use the `subset` parameter, which contains the list of columns to be checked.

In [8]:
df.duplicated(subset=['author'])

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27     True
28    False
29    False
30    False
31     True
32     True
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42     True
43    False
44    False
dtype: bool

Now I can calculate the number duplicates through the sum of `True` records.

In [10]:
df.duplicated().sum()

0

## Drop duplicates
Now I can drop duplicates through the `drop_duplicates()` function. I can use different strategies:
* drop all duplicates, on the basis of all the columns
* drop all duplicates, on the basis of some columns

In both the strategies, I can decide whether to maintain a copy of the duplicated values or not. This can be done through the `keep` parameter, passed as input to the `drop_duplicates()` function.

In [11]:
df1 = df.drop_duplicates()

In [12]:
df1.shape

(45, 8)

In [ ]:
df1.head()

                            ID  ...  TAG
0  facebook_corpus_msr_1723796  ...  OAG
1   facebook_corpus_msr_466073  ...  NAG
4   facebook_corpus_msr_462570  ...  CAG
5   facebook_corpus_msr_465051  ...  NAG
6   facebook_corpus_msr_450994  ...  CAG

[5 rows x 3 columns]

Drop also the first duplicate

In [ ]:
df2 = df.drop_duplicates(keep=False)
df2.head()

                             ID  ...  TAG
20   facebook_corpus_msr_472878  ...  NAG
21   facebook_corpus_msr_397830  ...  OAG
22  facebook_corpus_msr_2127013  ...  CAG
23  facebook_corpus_msr_2018572  ...  CAG

[4 rows x 3 columns]

In [ ]:
df2.shape

(4, 3)

Drop duplicates on the basis of a subset of columns

In [ ]:
df3 = df.drop_duplicates(subset=["Comments"])
df3.shape

(9, 3)

In [ ]:
df3.head()

                            ID  ...  TAG
0  facebook_corpus_msr_1723796  ...  OAG
1   facebook_corpus_msr_466073  ...  NAG
4   facebook_corpus_msr_462570  ...  CAG
5   facebook_corpus_msr_465051  ...  NAG
6   facebook_corpus_msr_450994  ...  CAG

[5 rows x 3 columns]